### ISSUE TITLE
Diff view linked from review does not respect "since"

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto-admin#1007]
@wagnerand mentioned this on IRC. On https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/staging/collections/addons/records, "details" shows `+3, -2` (which seems reasonable), but clicking the link brings you to https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/staging/collections/addons/history?since=1565358851545&resource_name=record, which shows every single history entry.

I guess this is a consequence of https://github.com/Kinto/kinto-admin/pull/950/files#diff-50ebfe1aba681ca97d97da33cda80c41, but I have to say rereading it now that I'm not really sure what's going on. I guess `since` isn't correct because the history record timestamps do not correspond to record timestamps? But it also seems like `since` is never respected any more... so why is it still in the type at https://github.com/Kinto/kinto-admin/blob/master/src/types.js#L103 and the link at https://github.com/Kinto/kinto-admin/blob/master/src/plugins/signoff/components.js#L466 ?

**Comment by leplatrem** [comment]
The PR #950 removes since filtering in buckets, collections, and groups. But it should still be taken into account for records.

> Note 1: we also have https://bugzilla.mozilla.org/show_bug.cgi?id=1572040 with a similar feedback/request. The full diff view is a lot more understandable...

> Note 2: I don't have my phone with me, so no Duo push to authenticate on the VPN.
