### ISSUE TITLE
Improve error messages in forms

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#104]
```
21:49:57 <Natouille> Errors
21:49:58 <Natouille>     name: does not match pattern "^[a-zA-Z0-9][a-zA-Z0-9_-]*$"
```

This depends on rjsf and https://github.com/mozilla-services/react-jsonschema-form/issues/155

**Comment by leplatrem** [comment]
Also: they appear on top, which requires scrolling

**Comment by alexcottner** [comment]
Possibly resolved in rjsf already

**Comment by alexcottner** [comment]
Seems like we're good now
![image](https://github.com/user-attachments/assets/3cd245db-2049-46fd-9d43-e44b59fab215)
