### ISSUE TITLE
[signoff] Crash when no read permission on source collection

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#1040]
- The collections list sidebar and the main collection data kept spinning, and there was an exception in the logs

- it seemed like anytime I tried to look at a collection I didn't have access to, or one related to it, I would get a permission denied network response, an inscrutable error in the console, and a loading spinner that would never go away. Nothing else in the UI would work after that
notably, trying to look at any Normandy collection, even ones I have access to, would trigger this because it would try and look at the workspace collection which I don't have access to

- i have read access to the main/normandy-recipes as an anonymous users: https://settings-writer.prod.mozaws.net/v1/buckets/main/collections/normandy-recipes
but trying to view that collection in the admin fails in the way i described above: https://settings-writer.prod.mozaws.net/v1/admin/#/buckets/main/collections/normandy-recipes/records
because it also tries to access the main-workspace version of that collection, which I don't have access to: https://settings-writer.prod.mozaws.net/v1/buckets/main-workspace/collections/normandy-recipes

**Comment by alexcottner** [comment]
May have been fixed by #3178
