### ISSUE TITLE
Harmonize wording around containers "settings", "properties", "attributes"

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#107]
We should stay consistent, eg. avoiding "Collection settings" then "Manage collection properties". While the technical term is "data", I'd rather go with "settings" always. Thougths?

**Comment by leplatrem** [comment]
*details* could also work (would include properties, permissions, history)

**Comment by leplatrem** [comment]
Also : it should be reflected in the URL (currently `edit`)

**Comment by n1k0** [comment]
*Parameters*, *Configuration* could work nicely as well. Decisions, decisions.

**Comment by leplatrem** [comment]
After a round of thoughts, I think I prefer *Attributes*. Especially because that's the term we use on the server docs, and it works for every kind of object (as well as records see #262)
