### ISSUE TITLE
Removing a record from the list comes back to a 404

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#1077]
- Sign in
- Go to the collection
- Create a record
- Remote it from the collection record list

![showcase](https://user-images.githubusercontent.com/229453/66117628-48948b00-e5d5-11e9-8188-927cb21c540f.gif)

**Comment by leplatrem** [comment]
Do you mean deleting a record from a collection? Can you provide a step-by-step?

**Comment by leplatrem** [comment]
I don't reproduce :/

**Comment by alexcottner** [comment]
Closing this one out. Looks like we fixed this one already, can't reproduce with current UI.
