### ISSUE TITLE
Improve wording on the field name

### ISSUE THREAD

**Issue by Natouille** [Kinto/kinto-admin#110]
![kinto_web_administration_-_2016-06-01_10 59 03](https://cloud.githubusercontent.com/assets/2006947/15703881/07ee1bb0-27e8-11e6-9f40-382683d71f84.png)

Field1, field2. The user doesn't know what is expected (Name ? Descrption ?)

**Comment by n1k0** [comment]
Ah, that really depends on the JSON schema configuration.
