### ISSUE TITLE
Improve behaviour of the erreor message when you validate a collection with an empty filed

### ISSUE THREAD

**Issue by Natouille** [Kinto/kinto-admin#111]
![kinto](https://cloud.githubusercontent.com/assets/2006947/15704808/8caeca4e-27ec-11e6-83ce-ea094f28381a.png)
If you validate a collection with an empty field, a tooltip appears near the empty field. And that tip disappear if you scroll.

It should be an error message instead of a tooltip

**Comment by n1k0** [comment]
refs https://github.com/mozilla-services/react-jsonschema-form/issues/159

**Comment by alexcottner** [comment]
Possibly already resolved by #3060

**Comment by alexcottner** [comment]
Fixed. We now scroll to the error field automatically.
