### ISSUE TITLE
Add cancel button next to submit button on the bucket creation page

### ISSUE THREAD

**Issue by Natouille** [Kinto/kinto-admin#112]
![kinto_web_administration_-_2016-06-01_10 35 54](https://cloud.githubusercontent.com/assets/2006947/15705116/1275c0be-27ee-11e6-997d-ee4387b47653.png)

**Comment by n1k0** [comment]
Fixed by https://github.com/Kinto/kinto-admin/commit/857765c59635ed0035fcf6ef64f5c1e17d316e81
