### ISSUE TITLE
Conflict with additional properties and internal fields

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#1133]
When editing an existing record, we get the following errors:
```
['schema'] is an invalid additional property
['id'] is an invalid additional property
['last_modified'] is an invalid additional property
```

The schema does not mention any of these...

**Comment by wagnerand** [comment]
I am now getting the following error when trying to edit an existing block:

`Invalid root object field configuration:uiSchema order list does not contain properties 'schema', 'id', 'last_modified'.`

**Comment by leplatrem** [comment]
![Screenshot from 2019-12-04 15-19-42](https://user-images.githubusercontent.com/546692/70150038-97c86c00-16a9-11ea-8e48-63c96934aab7.png)

**Comment by alexcottner** [comment]
Appears to no longer be an issue.
