### ISSUE TITLE
Records in a collection have no name or description shown

### ISSUE THREAD

**Issue by Natouille** [Kinto/kinto-admin#114]
![kinto_web_administration_-_2016-06-01_11 57 27](https://cloud.githubusercontent.com/assets/2006947/15705687/acd6c214-27f0-11e6-8cc9-61aed4c02ea1.png)

I don't know how I did that but I fisrt created 2 empty records and added names and desc after. But the liste still appears empty of name and desc, just Last mod.

NB: you can create records without any name or desc : is that normal ? No mandatory field ?

**Comment by Natim** [comment]
Yes they are not mandatory except if they are marked as required in the JSONSchema.
If you want to display them in the CollectionList you need to specify them in the displayFields (Collection option)

**Comment by Natouille** [comment]
Ok found why, I'll explain after lunch (and maybe in French cause it's lolilol)

**Comment by Natim** [comment]
@Natouille do not hesitate to join #kinto on freenode to discuss that live and in french

**Comment by Natouille** [comment]
yep

**Comment by Natouille** [comment]
OK I finally understood the whole bouzin :laughing:

**Comment by n1k0** [comment]
We should probably prevent an empty "displayField" array to trigger that behavior though.
