### ISSUE TITLE
Deleting a field displays ane error message on another field

### ISSUE THREAD

**Issue by Natouille** [Kinto/kinto-admin#115]
On create collection, il you delete the display field at the bottom of the page, you have an error message attached to the "collection name" field.
This error should only be displayed at validation of the form.

![kinto_web_administration_-_2016-06-01_12 06 43](https://cloud.githubusercontent.com/assets/2006947/15705944/93d9a8d4-27f1-11e6-8c78-5e9b254be147.png)

**Comment by n1k0** [comment]
Depends on https://github.com/mozilla-services/react-jsonschema-form/issues/221

**Comment by leplatrem** [comment]
Fixed apparently :)
