### ISSUE TITLE
[signoff] Rollback records get wrongly included into the diff view of the subsequent edit

### ISSUE THREAD

**Issue by ncloudioj** [Kinto/kinto-admin#1174]
STR:

* Create a new record in a collection
* Rollback this record
* Modify any other records in the same collection
* Request for review
* When reviewer opens the diff view, it also shows the rolled-back record

Expected behaviror is that the diff view only shows the change for that edit.

Note: it's just a visual confusion other than a physical messup, as the rollback won't be included in the subsequent edit if the request gets approved.

**Comment by leplatrem** [comment]
Thanks for reporting this Nan!
We may have some issues with rollback :( :( https://github.com/Kinto/kinto-signer/issues/832

**Comment by ncloudioj** [comment]
No problem! 

Please feel free to close this if it's a dup for the above one.

**Comment by leplatrem** [comment]
I investigated this issue, and with the current server code there's not much we can do. Indeed the server does not «generate» any history entry on rollback. And the client is dumb.
The diff view should be correct though. 
I think we can fix this by populating the history with changes operated by the rollback. Then we can choose, either the client remains dumb and shows «created XX, deleted XX» (which is concretely what happens) or it tries to be smart and can collapse creations and deletions. I would vote for the former.

**Comment by leplatrem** [comment]
We deployed a new version of the server where history shows details about the changes made during a rollback. This should at least help with the UI consistency :)
