### ISSUE TITLE
Bucket order on left column . What ? How ?

### ISSUE THREAD

**Issue by Natouille** [Kinto/kinto-admin#118]
What defines the order of teh bucket on the left ?

Creation date ?
Can we rearrange the order ? (ie : drag and drop ?)
If I have a looong list of buckets, it's gonna be a mess to see all that : maybe a "collapse all" button and a collapse on each bucket could be a plus.

**Comment by Natim** [comment]
Yes it is probably the last modification of the bucket metadata.

**Comment by n1k0** [comment]
> What defines the order of teh bucket on the left ?

last_modified desc

> If I have a looong list of buckets, it's gonna be a mess to see all that : maybe a "collapse all" button and a collapse on each bucket could be a plus.

We discussed this with @DirtyF and I suggested we should probably collapse buckets by default. We should also make the sidebar stick at a fixed position and offer scrolling when dealing with a long list of buckets. The idea is to always have the whole sidebar actionable while scrolling a possibly large page on the right.

**Comment by n1k0** [comment]
This is currently blocked by https://github.com/Kinto/kinto/issues/1060
