### ISSUE TITLE
A bug with displayField that can cause a crash

### ISSUE THREAD

**Issue by Natouille** [Kinto/kinto-admin#119]
What I did : 

1. Create a collection A and delete all *displayFields*
2. Go to another collection (B)
3. Go back to collection A (settings) and add 2 *displayFields* (with empty names) then submit : the system didn't run any error because field names
4. Go back to list of records for collection A

**BIM red error : t is null**

![kinto_web_administration_-_2016-06-01_15 06 26](https://cloud.githubusercontent.com/assets/2006947/15710464/6eba76c8-280a-11e6-9e5b-fb9f74027570.png)

**Comment by n1k0** [comment]
This should be fixed by #122
