### ISSUE TITLE
Switching from collection options to bucket options doesn't refresh the metadata.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#120]
Maybe it would be better to actually have a refresh button.

**Comment by n1k0** [comment]
Could you add precise reproduction steps? Couldn't reproduce.

**Comment by Natim** [comment]
Click on the collection settings gear and then on the bucket settings gear. The bucket metadata is not updated if it was on the server.

**Comment by n1k0** [comment]
I still don't get it :) this is what I experience using the demo https://youtu.be/mrZNq-BPmEk (bucket metadata are actually reloaded each time we navigate to the bucket settings page)

**Comment by n1k0** [comment]
@Natim poke; I still don't understand this issue :)

**Comment by n1k0** [comment]
@Natim I'm gonna close this one but feel free to reopen if you manage to reproduce in a predictable fashion.

**Comment by Natim** [comment]
Ok
