### ISSUE TITLE
[minor] Validate uiSchema during collection creation/edition

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#138]
Error appears while adding record otherwise:
![capture d ecran de 2016-06-10 10-23-13](https://cloud.githubusercontent.com/assets/546692/15958353/5c9c3f2a-2ef5-11e6-8ae8-737c6f8ed08e.png)

It is enough for our current use-cases, but could be helpful for new comers

**Comment by n1k0** [comment]
Will do
