### ISSUE TITLE
Add GitLab as an login provider

### ISSUE THREAD

**Issue by vanillajonathan** [Kinto/kinto-admin#1425]
Add support for using GitLab as OpenID Connect identity provider.

https://docs.gitlab.com/ee/integration/openid_connect_provider.html

**Comment by leplatrem** [comment]
What is this? A feature request? :)

**Comment by vanillajonathan** [comment]
Yes, this is a feature request.

**Comment by Natim** [comment]
@vanillajonathan I encourage you to start this, We have a lot of providers already so you can copy all the tests and when they pass you will be all set.
- [kinto-portier](https://github.com/Kinto/kinto-portier)
- [kinto-facebook](https://github.com/Kinto/kinto-facebook)
- [kinto-fxa](https://github.com/Kinto/kinto-fxa)

You may also be able to leverage [kinto-openid](https://github.com/Kinto/kinto/tree/master/kinto/plugins/openid) for Github.

**Comment by Natim** [comment]
## Configuration

1. Register an OAuth application on GitHub: https://github.com/settings/applications/new
2. Note the new application's client ID and secret.
3. Configure kinto-openid with the following:

```ini
kinto.includes = kinto.plugins.openid

multiauth.policies = github

multiauth.policy.github.use = kinto.plugins.openid.OpenIDConnectPolicy
multiauth.policy.github.issuer_url = https://github.com
multiauth.policy.github.client_id = GITHUB_CLIENT_ID
multiauth.policy.github.client_secret = GITHUB_CLIENT_SECRET
multiauth.policy.github.userid_field = email
```

**Comment by Natim** [comment]
Ok sorry I wrote all this about Github while you were talking about Gitlab.

```ini
kinto.includes = kinto.plugins.openid

multiauth.policies = gitlab

multiauth.policy.gitlab.use = kinto.plugins.openid.OpenIDConnectPolicy
multiauth.policy.gitlab.issuer_url = https://gitlab.com
multiauth.policy.gitlab.client_id = GITLAB_CLIENT_ID
multiauth.policy.gitlab.client_secret = GITLAB_CLIENT_SECRET
multiauth.policy.gitlab.userid_field = email
```

**Comment by vanillajonathan** [comment]
It would be nice if this was setup on the demo server.

**Comment by Natim** [comment]
You can use the kinto-heroku deploy button to try it.

**Comment by vanillajonathan** [comment]
I see.
