### ISSUE TITLE
Loading indicator not shown when loading history

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#1596]

**Comment by alexcottner** [comment]
Should be fixed with my next MR. See video below.

[Video link here](https://github.com/Kinto/kinto-admin/assets/148472676/52a9d2c1-5fe2-4b76-b941-c1291362e143)

**Comment by alexcottner** [comment]
Closed with [PR 3050](https://github.com/Kinto/kinto-admin/pull/3050).
