### ISSUE TITLE
Unable to request the permissions endpoint: Failed to fetch

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#178]
> acao: i'm trying to get kinto server to be configured similar to the kinto-admin example
> acao: and i'm getting "Unable to request the permissions endpoint: Failed to fetch"
> acao: i'm sure it's something very simple i'm overlooking. i used the docker compose example, then peppered in some of the configs from the heroku example, and now i'm trying to recreate the configs i see in the kinto-admin demo y'all have
> acao: the base / route shows readonly: false
> 

We made a mistake. We check the server version to fetch from the permissions endpoint. But we did not enable it by default on the server :/ 

What do we do ? Shall we enable it by default on the server ? Shall we add a public setting on the server and check for it here ? What do you guyz think ? /cc @n1k0 @Natim

**Comment by n1k0** [comment]
As to me this is an important and useful core feature, it should be enabled by default, but that may just be me.

**Comment by Natim** [comment]
Until it is not experimental anymore I would be in favor of adding a capability. Plus this would let use keep compatibility with older version of Kinto.

**Comment by leplatrem** [comment]
Fixed in https://github.com/Kinto/kinto-admin/pull/181
