### ISSUE TITLE
Read the list of collections in the selected bucket and read the schema in the collection.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#18]
Now that xml2kinto creates the collection with the schema, this could be a nice to have for https://github.com/mozilla-services/amo-blocklist-ui

**Comment by n1k0** [comment]
I thought we decided to have this very repo being the unique source of truth for the schema definitions?

**Comment by n1k0** [comment]
But yeah, in the future when we migrate the admin from kinto.js to kinto-client, we'll be able to browse buckets, collections and read/update their schemas.

**Comment by Natim** [comment]
> I thought we decided to have the amo-blocklist-ui repo being the unique source of truth for the schema definitions?

This would still be the case even when kinto-admin will read the schema from kinto because at some point you need to setup the collection by providing the schema.

Having "the amo-blocklist-ui repo being the unique source of truth" doesn't mean that kinto-admin read the amo-blocklist-ui.json file to generate schema. However this is not P1 and as soon as both schema stays in sync we should be fine.

**Comment by n1k0** [comment]
Fixed by #65.
