### ISSUE TITLE
Record update permissions are not recognized for owner of bucket/collection.

### ISSUE THREAD

**Issue by doplumi** [Kinto/kinto-admin#186]
kinto-admin doesn't seem to recognize update permissions on records for owners of buckets/collections containing those.

#### Steps to reproduce ####

1. Create a bucket `b` with user `A`
2. Create a collection `c` with the same user `A`.
3. Create a record `r` with a user `B`.
4. User `A` won't be able to update the record via kinto-admin even though it can via http API.

####  Additional info ####

When a record is created in a collection by a certain user `B`, that record will be of the type:
```
{ 
  "data": { ... }
  "permissions": {
    "write": [
      "B"
    ]
  }
}
```
and there is nothing written on the record about the owner of the collection,

However, after updating via HTTP API with the owner of the collection, user `A` is added to the `write` array, as in `permissions: { write: [ "A", "B" ] }`. After this, kinto-admin will start allowing updates from user `A`, as per expected initial behavior.

**Comment by Natim** [comment]
Hello @doplumi which version of the kinto-admin are you using? Have you got the permissions endpoint activated on your server?

**Comment by n1k0** [comment]
There's something I don't clearly understand in the reproduction steps:

> 1. Create a bucket `b` with user `A`
> 2. Create a collection `c` with the same user `A`.
> 3. Create a record `r` with a user `B`.

User `B` doesn't have natural access to this collection; how did you configure it from the admin so this user can create records within it? 

User `B` getting a 403 when attempting to create the record in this collection is expected. What permissions did you set for the `c` collection?

**Comment by doplumi** [comment]
@n1k0: You're right, I forgot to report one step between 2 and 3. 
Let's call it step 2b. It is the execution of the command

```
echo '{ "permissions": { "read": ["system.Everyone"], "record:create": ["system.Authenticated"] } }' | http PUT https://<domain>:<port>/v1/buckets/public/collections/<collectionName> \
    --auth <username>:<password>
```

where `<token>:<secret>` are the credentials of user `A`.

@Natim: I'm using the hosted version of kinto-admin.

**Comment by n1k0** [comment]
Okay thanks I just wanted to be sure. So we need to check for parent container permissions, fortunately we have this information in the reducers, so shouldn't be too hard. Thanks for the report.

**Comment by mariustresor1** [comment]
Same problem encountered with trombinoscope: a new instance of "people" created from the front page by annymous user cannot be modified by the admin.

**Comment by n1k0** [comment]
> Same problem encountered with trombinoscope: a new instance of "people" created from the front page by an anonymous user cannot be modified by the admin.

I'm confused, isn't this a server configuration issue rather than an admin one?

**Comment by Natim** [comment]
> I'm confused, isn't this a server configuration issue rather than an admin one?

No the config on the server is correct. I created a patch to show you what is missing here: #240
