### ISSUE TITLE
History of changes

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#187]
If the server has the `history` capability we can present the history for every object in a separate view.

It could be a link along the parameters : 
![screen shot 2016-08-18 at 18 36 21](https://cloud.githubusercontent.com/assets/546692/17782196/b130f7fc-6572-11e6-85ce-7ff42f1e8b67.png)

Or it could be a tab in the parameters view. Since records will eventually parameters too (eg. permissions), it may be the best approach: each object would have a parameter view, with tabs (metadata, permissions, history). 

The history should not be loaded unless explicitly requested by the user.
IMO it is acceptable if the tab is present but shows an error when accessed if the server does not have the `history` capability (KISS).

* Requires https://github.com/Kinto/kinto-http.js/pull/125

**Comment by n1k0** [comment]
WiP :)

![](http://i.imgur.com/TSF3jjn.png)

**Comment by n1k0** [comment]
Note: the rationale behind not rendering history in the parameters view is than I'm planning to introduce tabs for creating/editing a collection (related: #150), and I don't really want tabs within tabs. Also, implementation is *much* simpler using a dedicated view, yet very efficient.

**Comment by leplatrem** [comment]
Fixed by #196
