### ISSUE TITLE
Remove an entry when there is an attachment.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#188]
I didn't see where I could delete a record:

I think a button in the Edit part could be nice:

![capture du 2016-08-19 11-57-07](https://cloud.githubusercontent.com/assets/229453/17806350/4a92e1bc-6604-11e6-80e7-9600fdf1c407.png)

Apparently the button in the list is not accessible when there is an attachment:

![vue liste](https://cloud.githubusercontent.com/assets/229453/17806361/5cf278cc-6604-11e6-8f03-636bf7f22668.png)

**Comment by n1k0** [comment]
Released in [v1.2.1](https://github.com/Kinto/kinto-admin/releases/tag/v1.2.1).
