### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#189]
When using the ``kinto-admin build -d kinto_admin/static/`` script to package the kinto-admin it seems that the font are not loaded correctly.

See: https://github.com/mozilla-services/kinto-dist/blob/master/Makefile#L44-L48

![kinto-writer-font](https://cloud.githubusercontent.com/assets/229453/17806527/6d9a2f3e-6605-11e6-867b-635a8aa6ef4e.png)

**Comment by n1k0** [comment]
You need to set the `KINTO_ADMIN_PUBLIC_PATH` env var to the exposed absolute path url of the assets folder before running `npm run dist`, as you can see in `package.json` commands.

**Comment by n1k0** [comment]
See #190 for docs patch.

**Comment by n1k0** [comment]
Fixed by #189. Underlying issue will be fully addressed by #192.
