### ISSUE TITLE
Escaping of quotes

### ISSUE THREAD

**Issue by k88hudson** [Kinto/kinto-admin#1929]
<img width="564" alt="image (6)" src="https://user-images.githubusercontent.com/1455535/123143940-1d953f00-d429-11eb-9d33-598161d97d0c.png">

Looks like quotes are getting escaped

**Comment by piatra** [comment]
Might also be an edge case, looking at the string again it mixes `"` and `'` in the same expression and the string also includes an `\` escape character which is gets escaped when shown.
My problem here was that I thought the "real" value actually had `\\\` in it which would have been strange/needed to be changed.

**Comment by k88hudson** [comment]
I think this either user error or something weird with the remote settings generated inputs now that I have investigated it. Not a display issue.

**Comment by leplatrem** [comment]
What do you mean by *generated inputs*?

Can you send the collection id / record id?

**Comment by piatra** [comment]
This was the string

> ctx.channel == "release" && ctx.version|versionCompare('89.!') >= 0 && 'app.shield.optoutstudies.enabled'|preferenceValue && ctx.localeLanguageCode == 'en' && ctx.region == 'US' && 'browser.urlbar.showSearchSuggestionsFirst'|preferenceValue && [ctx.userId, "urlbar-1"]|bucketSample(1500, 8500, 10000)

It mixes `"` and `'`. It shows up like this when editing the record:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/810040/123449797-87e5e500-d5cb-11eb-87e7-5c4500fbf758.png">

But in the review panel it showed up like in comment 1.
