### ISSUE TITLE
[simple-review] Add query param to hide rollback button

### ISSUE THREAD

**Issue by k88hudson** [Kinto/kinto-admin#1953]
For experimenter usage, we do not want people to trigger a rollback via the UI.

It would be nice to be able to hide the button with a query param (to be put in links in Experimenter UI)

See https://github.com/mozilla/experimenter/blob/6e08fa198b07324b412543246390c0dab046cd7c/experimenter/experimenter/experiments/models.py#L679-L686

**Comment by alexcottner** [comment]
Resolved with last PR
