### ISSUE TITLE
Persistent sessions ? 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#211]
Use cases

* Alice sends a link to an object to Bob. Since Bob had authenticated him with the Kinto-admin a few hours earlier, he can open the page on the object directly
* During development, I refresh the page. I have to login again and go back to the page I was hacking

**Comment by n1k0** [comment]
We could store current session information in [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API).
