### ISSUE TITLE
Use official Enzyme test adapter when it is available for React 17

### ISSUE THREAD

**Issue by grahamalama** [Kinto/kinto-admin#2159]
In order to bump React to the latest version in #2209, we had to install an [unofficial Enzyme adapter](https://github.com/wojtekmaj/enzyme-adapter-react-17) that supported React 17. When Enzyme releases a test adapter that supports React 17 (tracked [here](https://github.com/enzymejs/enzyme/issues/2429)), we should uninstall the unofficial package and use the official Enzyme package.

**Comment by grahamalama** [comment]
Closing this issue for now since we rolled React back to v16 in #2182

**Comment by alexcottner** [comment]
PR has been merged. Enzyme has been removed. Marking issue as closed, although we have more work to follow up on.
