### ISSUE TITLE
Reuse notification system for form validation errors

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#22]
(_not a priority_)

Might require some work on react-jsonschema-form to prevent it to add the validation messages in the DOM, and let the user handle them in the `onError` callback.

Imported from https://github.com/mozilla-services/amo-blocklist-ui/issues/20

**Comment by alexcottner** [comment]
Possibly resolved with #3060 , but in a different way

**Comment by alexcottner** [comment]
Marking as resolved. Now that we're using the rjsf components, this is handled for us in another way.
