### ISSUE TITLE
[signoff] Simple Review should disable the approve/reject buttons after they're clicked

### ISSUE THREAD

**Issue by jaredlockhart** [Kinto/kinto-admin#2206]
Currently, when a user clicks approve or reject, the button remains enabled while the API call is being made with no visual indication and the buttons are still enabled so there's nothing preventing someone from clicking them multiple times.  We should disable the buttons while the API call is being made to prevent users from firing multiple requests.

**Comment by leplatrem** [comment]
See also https://github.com/Kinto/kinto-admin/issues/1360

**Comment by alexcottner** [comment]
Closed with [PR 3050](https://github.com/Kinto/kinto-admin/pull/3050).
