### ISSUE TITLE
[signoff] Offer ability to use simple-review as default review UI

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#2269]
In https://github.com/Kinto/kinto-admin/pull/1885 an alternative review UI was introduced.

We want to make this UI as default, and offer the ability to switch to the old one for users that don't like it.

Users could be presented a «switch to old review» toggle, with the preference stored in local storage.

Related #1953 

⚠️ Experimenter has `simple-review` in its URLs https://github.com/mozilla/experimenter/blob/6e08fa198b07324b412543246390c0dab046cd7c/experimenter/experimenter/experiments/models.py#L679-L686

**Comment by alexcottner** [comment]
Adding notes from [bugzilla Bug 1572040](https://bugzilla.mozilla.org/show_bug.cgi?id=1572040).

> Mike (Connor) mentioned to me that approving changes to remote settings is difficult to understand.
>
>On the approval page there's two links:
>
>    Preview - which takes you to something that looks very much like the same page as the approvals page.
>    Changes - this gives you a list of details.
>
>The preview in itself doesn't seem very useful, as you'd still need to dig into each section to see the details.
>
>The list of changes are a bit of a pain to read, as there's lots of noise from non-user changes, and no clear details of what's actually changed.
>
>When you find the diff view, it looks like the diff is a reverse diff - although we've only added things, they're indicated as removals, which is a bit strange.
>
>Maybe this could be improved in a couple of ways:
>
>    Make the "Changes" to something like "Show differences" that takes you to a correct diff view straight away. Make it the first, primary link.
>    Change "Preview" to something like "Show all" and possibly redirect it to the json, or keep it where it is at the moment.

**Comment by leplatrem** [comment]
My proposal:

When the collection is signed or work-in-progress:
* Keep the current UI (ie. `RecordTable` + `SignoffContainer`)

When the collection is to-review:
* unless user opted-out, replace all the current UI with the simple-review page
* on the simple-review page, add a link to the preview collection (`"collection:records" {previewBucket} {cid}`) with label `Show all` to allow users to inspect the list of records to be published if approved
* on the preview collection, add a back link to the workspace collection with label `Show pending changes` to navigate back (the label would make less sense for opted-out users, but I think this is acceptable)
