### ISSUE TITLE
Bucket list is ugly as soon as multiple apps use the same service

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#234]
Just try to use the kinto-admin with kinto.notmyidea.org you will see what I mean.

![example](https://cloud.githubusercontent.com/assets/229453/18317314/ff380dfe-751d-11e6-9984-e98f18646bf4.png)

To start with I think we should display only bucket with the `write` permission somewhere.
The we could add `record:create` flag to have a bit more and finally a `read` but by default write seems to be enough in the Sidebar.

It doesn't mean that we cannot directly access another collection that is not in the sidebar. But displaying all the bucket the user can access to is quite confusing for users.

**Comment by n1k0** [comment]
I wouldn't go as far as *ugly* but I get your point. We could expose a way to filter the list of buckets in the sidebar, listing only those you have write access to by default, or allow listing them all with a click of a button.

We should also add a new view for listing all the buckets, with action buttons for each row like we do for bucket collections and collection records; that would come handy when dealing with dozens of buckets.

Note that is may be slightly connected with #86 and #118 as well.

**Comment by n1k0** [comment]
I usually hate them, but I wonder if using an Accordion widget could improve the UX a little here; basically we'd have all buckets collapsed by default, and clicking on one would expand the list of collection entries as we know it today. Thoughts?

**Comment by Natim** [comment]
The problem is not really the size of the sidebar it is just that you don't want to see other people buckets apps even if you could use their app.

**Comment by Natim** [comment]
I agree with you when you want to use the kinto-admin to browse the data on the server and we should keep this option available.

However most of the time the admin is used to add some data and in that case it can be really helpful to see only the collections that you want to administrate.

**Comment by leplatrem** [comment]
Fixed with #385
