### ISSUE TITLE
[signoff] List of records is not refreshed after rollback 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#2361]
Steps to reproduce: 

- Use an empty collection
- Create a record, status is work in progress
- Click *Rollback*
- Status is back to signed, but record is still present and tab says *Records (1)* 
- Click on the Records tab to reload the page, list of records is empty

Expected:
- list of records should be refreshed (ie. empty) after rollback

**Comment by alexcottner** [comment]
Resolved with last PR
