### ISSUE TITLE
Refactor the JSONEditor component

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#237]
Spwaned from #204:

> For JSON fields, it would be nice if the stringification and parsing would be done in the same place (both at the form level) : https://github.com/Kinto/kinto-admin/blob/v1.3.0/scripts/components/BucketForm.js#L79-L80 https://github.com/Kinto/kinto-admin/blob/v1.3.0/scripts/components/BucketEditForm.js#L31-L32

**Comment by alexcottner** [comment]
Closed with [PR 3043](https://github.com/Kinto/kinto-admin/pull/3043).
