### ISSUE TITLE
little notification "cross" is in position: fixed

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto-admin#24]
This little cross (see screenshot below, its css class is `close`) is set as `position: fixed`, and will thus stay exactly in the same position when scrolling.

It's also not properly aligned with the notification box title.

 <img width="59" alt="screen shot 2016-03-22 at 10 48 29" src="https://cloud.githubusercontent.com/assets/167767/13947582/aac75874-f01b-11e5-9c10-ec534965487d.png">

**Comment by Natim** [comment]
A position: relative in the parent block should fix the matter.
