### ISSUE TITLE
Don't store sidebar state in saved session data

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#245]
When loading the admin restoring a previously saved session, the state of the sidebar (the list of buckets and collections) is restored as well, while these data might be quite heavily outdated; while the new list is loaded, the sidebar renders links to possibly deleted buckets and collection, and if users click on these, they'll get 403 or 404 errors.

We should ensure clearing these specific data before saving a full session dump to localStorage, so we never render them after a session is reloaded.

**Comment by Natim** [comment]
:+1:
