### ISSUE TITLE
Filter out members from group metadata when updating

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#273]
- Go to a group with several members
- Enter `{"members": []}` in _Group metadata_
- Observe that the list of members is now empty :)

**Comment by sunakshi96** [comment]
Hey 
I tried that thing out. There is no need to fill the members field. If we keep it at the default state="{}". It is showing members.
And I also entered the {"members": []} in Group metadata which means we are explicitly indicating that the member field should  remain empty. 

![screenshot from 2016-10-13 10-40-36](https://cloud.githubusercontent.com/assets/9900938/19337297/74f34f66-9131-11e6-8fb2-a2354d22c00c.png)
![screenshot from 2016-10-13 10-40-16](https://cloud.githubusercontent.com/assets/9900938/19337298/7503eb78-9131-11e6-80e5-6f0572f2e483.png)
![screenshot from 2016-10-13 10-39-33](https://cloud.githubusercontent.com/assets/9900938/19337299/75142b32-9131-11e6-97f3-fbefe3f7cb55.png)

**Comment by sunakshi96** [comment]
And also if we fill only the fields group id and metadata field like ::
group id:101
metadata:{"members":["member1","member2"]}(by not adding the member using add button)
Then the group created is showing the members.

**Comment by sunakshi96** [comment]
Can we create a sort of authentication which will first verify whether the members are already present or not, if yes then a dialog box should display which will ask whether to add or delete members or not?

**Comment by leplatrem** [comment]
I think we should just ignore the `members` attribute specified in the metadata.

**Comment by n1k0** [comment]
Another example:

Form:

![](http://i.imgur.com/dWXYnb5.png)

Result:

![](http://i.imgur.com/MW3qx3w.png)
