### ISSUE TITLE
Rename «history» for server urls to something else

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#283]

**Comment by sunakshi96** [comment]
Hey 
Can "Account-Details"  work a substitute for history?

**Comment by leplatrem** [comment]
Sorry I didn't provide much details.
I was referring to this https://github.com/Kinto/kinto-admin/blob/773ef8cad8924bd23f2925a830d87948efb0b656/src/actions/history.js
which stores the server URLs that were entered by the user.

Some possible names for these would be: 
* previous server urls
* server url history
* ...

But just `history` is confusing now that we have pages with the history of objects
