### ISSUE TITLE
Migrate away from container components in favor of functional compomnents with `react-redux` hooks

### ISSUE THREAD

**Issue by grahamalama** [Kinto/kinto-admin#3026]
We started this process in https://github.com/Kinto/kinto-admin/pull/2378 (quoting from that issue)

> In this PR, we start the process of removing "container" components from throughout the app where we `map{State, Disptach}ToProps`. Instead, we'll use [`react-redux` hooks](https://react-redux.js.org/api/hooks) to provide dispatch and Redux store values to components. This will lead to an overall fewer number of components to manage, which is a plus.

and continued it in https://github.com/Kinto/kinto-admin/pull/2443 and https://github.com/Kinto/kinto-admin/pull/2403.

This issue can track finishing that process.

**Comment by alexcottner** [comment]
Closed with [PR 3043](https://github.com/Kinto/kinto-admin/pull/3043).
