### ISSUE TITLE
In the list of record clicking the attachment link is invalid.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#303]
It is linking to `https://kinto-writer.stage.mozaws.net/v1/admin/fennec/catalog/f0459232-7b26-4193-b568-5212ad6e858a.gz`
when it should be `https://net-mozaws-stage-kinto-fennec.s3.amazonaws.com/fennec/catalog/f0459232-7b26-4193-b568-5212ad6e858a.gz`

It is like if the `base_url` from the home page `attachment.base_url` wasn't used.

**Comment by n1k0** [comment]
> It is like if the base_url from the home page attachment.base_url wasn't used.

It's not, will fix.
