### ISSUE TITLE
`.authType should be equal to one of the allowed values` error on login page

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#3065]
<img width="1007" alt="Screenshot 2023-11-17 at 10 53 08" src="https://github.com/Kinto/kinto-admin/assets/546692/77e0a48f-98c7-4c1a-bb92-eb6f5cad12ab">

See https://github.com/mozilla/remote-settings/issues/229
See https://bugzilla.mozilla.org/show_bug.cgi?id=1865230
See https://mozilla.slack.com/archives/CBGR8AW6R/p1700178464489389

**Comment by alexcottner** [comment]
I _think_ this has been resolved with the v2.1.x kinto-admin changes, likely when I rewrote AuthForm to be a functional component. Pending confirmation from a user who was experiencing the issue, but they haven't encountered it recently.

**Comment by alexcottner** [comment]
Closing this out as we can no longer reproduce the error.
