### ISSUE TITLE
Spinner should be within container when navigating tabs

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#3069]
When navigating tabs, I believe it would feel more pleasant if the spinner would remain within the container, instead of making tabs disappear/reappear

https://github.com/Kinto/kinto-admin/assets/546692/0ab0a4cd-6855-4abc-9e28-aa25bbba60a9

**Comment by leplatrem** [comment]
It seems to be the behaviour of the `Records` tab already:

https://github.com/Kinto/kinto-admin/assets/546692/fe8d6fa6-132a-45aa-bac8-258c521b32fb

**Comment by alexcottner** [comment]
Resolved in #3226
