### ISSUE TITLE
Trying to view certain collections with `anonymous` auth leads to endless loading spinners across the app

### ISSUE THREAD

**Issue by grahamalama** [Kinto/kinto-admin#3073]
Steps to reproduce:

- log into https://remote-settings-dev.allizom.org/v1/admin/#/ with anonymous `auth`
- Check `Show readonly buckets/collections`
- Click on `addons` collection in the `blocklist` bucket
- Result:
<img width="1353" alt="image" src="https://github.com/Kinto/kinto-admin/assets/20747904/b0291dff-9d4a-498f-9fb5-43bf78de363f">
In the console:
<img width="783" alt="image" src="https://github.com/Kinto/kinto-admin/assets/20747904/4f5f0fd0-17f7-495b-bf91-6c548dd2dcc5">

- Try to navigate back home and click the "refresh" button for collections:
<img width="1365" alt="image" src="https://github.com/Kinto/kinto-admin/assets/20747904/03db3c42-86a2-4f38-b330-ca6a382c7a8e">

**Comment by alexcottner** [comment]
Mixed news, this isn't a fully new issue but this release definitely makes it easier to get into a bad state. I started seeing all sorts of weirdness when using anonymous auth and can reproduce most of this in the v2.0.0 UI. See video below.

[video demo](https://github.com/Kinto/kinto-admin/assets/148472676/be209a6d-0f57-4f1a-945a-d2970a60015e)


The correct answer is obviously to fix all of this, but that's going to delay this release more than we'd like. This release is an improvement in many ways, so I think for the short term I'm going to:
1. Create a bug noting all of these issues with anonymous auth (it could be issues for users lacking permissions in general). We definitely have an issue where redux gets into a bad state with `session.busy`, hence the spinners getting stuck.
2. Patch this so we're at least not making the problem _worse_, by doing some additional permission checks and returning errors.
