### ISSUE TITLE
The "Edit Raw JSON" UI does not respect "Attachment required"

### ISSUE THREAD

**Issue by nordzilla** [Kinto/kinto-admin#3128]
### Defect Description

For a collection, it is possible to make attachments required for all records:
```json
"attachment": {
  "enabled": true,
  "required": true
},
```

This setting is respected in the "Edit form" UI of the admin dashboard, see the text in the image below that says "Please select a file." when the update-record button is clicked.
![image](https://github.com/Kinto/kinto-admin/assets/58569820/b1f5f1a5-1474-4ff8-83fc-f2949652430f)

However, moving to the "Edit raw JSON" UI enables you to click the update-record button with no error pop-up. This effectively updates the record and removes the attachment, even though attachments are required for the collection, leaving things in an invalid state. 

---
### Steps to reproduce
1) Create a collection with attachments required.
2) Create a record with a valid attachment.
3) Navigate to the edit-record page for that record.
4) Click the update-record button on the "Edit form" UI and observe the error pop-up.
5) Navigate to the "Edit raw JSON" UI and click the update-record button.

##### Expected Outcome
> An error pop-up saying "Please select a file." should appear, just like the "Edit form" UI.
##### Actual Outcome
> The record is updated with no attachment, effectively removing the attachment, even though attachments are required.

**Comment by alexcottner** [comment]
I'd like to propose a slightly different solution. If attachments are required and you're updating a record, if you don't include a new attachment it should keep the existing one. Does that sound reasonable or does it make more sense to always require a new attachment?

**Comment by nordzilla** [comment]
> I'd like to propose a slightly different solution. If attachments are required and you're updating a record, if you don't include a new attachment it should keep the existing one. Does that sound reasonable or does it make more sense to always require a new attachment?

Definitely! I think that would be ideal behavior. 

Thank you!

**Comment by leplatrem** [comment]
> If attachments are required and you're updating a record, if you don't include a new attachment it should keep the existing one. 

That is (or was at least) the behaviour when using forms, so it would be consistent with this fix
