### ISSUE TITLE
[Signoff] Errorenous time representations

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#316]
Some dates are clearly wrong and/or poorly formatted: 

![screenshot at 16 40 11](https://cloud.githubusercontent.com/assets/41547/20312092/85c4f93a-ab52-11e6-80f4-423616aa2ffb.png)

**Comment by Natim** [comment]
Note the 46 years ago pretty confusing.

**Comment by leplatrem** [comment]
`in 2 minutes`: we want to use the local timezone to display the UTC timestamp, but it should not be shifted (e.g. here local clock is 2 minutes late)

`46 years ago`: if no changes were made, the `lastChanged` timestamp is null which might lead somewhere around 1/1/1970 :)
