### ISSUE TITLE
`</strong>` shown in attachment form

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#3192]
<img width="554" alt="Screenshot 2024-03-22 at 16 46 55" src="https://github.com/Kinto/kinto-admin/assets/546692/0765bdd6-a3a5-408e-adaa-3078b43d519a">

**Comment by alexcottner** [comment]
Looks like this was an [issue in rjsf](https://github.com/rjsf-team/react-jsonschema-form/pull/4125) and the fix was released in rjsf v5.18.1. Will merge the dependabot PRs and we'll be fixed.

![image](https://github.com/Kinto/kinto-admin/assets/148472676/ad8626b9-7b36-417b-9581-6178c9d5ff01)
