### ISSUE TITLE
Show heartbeat status in top bar 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#3220]
Like with a red/green circle and a blank target link to the endpoint

Would serve as a *is it down for everyone or just me* indicator

**Comment by alexcottner** [comment]
Should we make this an optional feature that can be enabled in server config?

I could see a scenario where there are several concurrent users and the heartbeat checks are somewhat expensive (depending on the plugins and level of checking).

**Comment by leplatrem** [comment]
Good point, but I think it's fine if we check it like on the login page when fetching capabilities, and then maybe once every minute or so.
We also have Telscope that fetches it regularly too. We could chose to add a microcache on the server if that becomes necessary
