### ISSUE TITLE
We need to find a way to hide read only buckets and collection in the kinto-admin sidebar.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#323]

**Comment by n1k0** [comment]
Don't we want people to read data too?

**Comment by leplatrem** [comment]
What is the rationale?

Links to preview and destination in the signoff plugin will be broken...

**Comment by Natim** [comment]
Why should they be broken? Hidding them from the sidebar doesn't mean they shouldn't be able to access them.

**Comment by leplatrem** [comment]
Fixed with #382
