### ISSUE TITLE
Fetch authentication methods from server capabilities

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#331]
* User picks a server
* Capabilities are fetched
* Known authenticated methods are filtered against the methods that the server supports

**Comment by n1k0** [comment]
I'm gonna work on this.

**Comment by Natim** [comment]
I guess our main use case now for the kinto admin is the plugin for a given server.
I think we should expose the server settings with a Javascript file created from the server config and ignore this when the server is not configured.

**Comment by Natim** [comment]
I believe we can close that since we've fixed it with the kinto-admin plugin here: https://github.com/Kinto/kinto/pull/1041

**Comment by leplatrem** [comment]
I'm not sure we should have closed this.

It's indeed sorted out when kinto-admin is served via Kinto, but it's still relevant when targeting a specific server from Github pages. Every authentication method will be shown where the server is likely to support only one or two.
