### ISSUE TITLE
Add an encryption plugin

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#333]
If the collection contains an encrypted payload, ask for the decryption key.
This would be useful to be able to browse the data stored by webextension and by sync using Syncto.

**Comment by Natim** [comment]
See https://github.com/mozilla-b2g/gaia/blob/master/shared/js/sync/crypto/fxsyncwebcrypto.js

**Comment by leplatrem** [comment]
Won't happen :)
