### ISSUE TITLE
Do not store password in localStorage

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#364]
Maybe sessionStorage instead?

**Comment by n1k0** [comment]
why?

**Comment by Natim** [comment]
It is a bit dangerous to have some critical passwords unencrypted on the browser.

**Comment by n1k0** [comment]
Is it just for passwords or tokens as well?

**Comment by Natim** [comment]
I wish it was the case at least for LDAP passwords. Maybe we should have different policies for each auth plugin?

**Comment by n1k0** [comment]
We could also store the auth token generated after a succesful LDAP authentication instead of the password in clear? Or would that be still too sensitive?

**Comment by Natim** [comment]
We don't have such thing (auth token) with the current LDAP setup. It is using BasicAuth so the username/password are sent as a bas64 encrypted Authorization header.

If we move to auth0, we would be able to do that.

**Comment by Natim** [comment]
This is really important.
