### ISSUE TITLE
Add a way for user to hide readonly buckets from the sidebar

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#376]
Especially using the kinto-signer plugin it is quite confusing and we have a lot of incomprehension by people trying to update a readonly bucket collection and filling bugs telling that they don't have the permission to edit the data. (i.e in blocklists-preview and blocklists buckets)

**Comment by n1k0** [comment]
What would be the best/most efficient way to identify read-only buckets? Can we easily infer this information from the permissions endpoint?

**Comment by Natim** [comment]
Yes I guess using the permissions endpoint for this is a good idea.
