### ISSUE TITLE
Remove property from existing entry in collection

### ISSUE THREAD

**Issue by pocmo** [Kinto/kinto-admin#377]
For our A/B experiments we have a collection of entries that look like this (simplified):

```json
{
    "name":"offline-cache",
    "last_modified":1482264657139,
    "id":"5e4277e0-1029-ea14-1b74-5d25d301c5dc",
    "match": {
        "appId":"^org.mozilla.fennec.*$"
    }
}
```

Some experiments we limit to specific app versions using for example the "appId" property in the example above. If we decide to later remove this restriction then we can't do this with the web admin. We could clear it but then we still have this empty property in the JSON and we need to special case this situation in our app. Instead it would be super helpful to be able to remove a property (instead of just clearing it).

Workaround in Fennec:
https://bugzilla.mozilla.org/show_bug.cgi?id=1335355

**Comment by n1k0** [comment]
This would be nicely solved by upgrading [react-jsonschema-form to v0.42.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.42.0), which now clears a text field when the input is updated to just contain a blank string.

Meanwhile, you can also edit the raw JSON contents for a record, where you can manually drop the property value.

**Comment by n1k0** [comment]
I've just tested upgrading rjsf to v0.42, there's still an issue with us PATCHing records instead of PUTting them, so there's no way to actually drop a property. This is a bug, I've filed #378 about it.

**Comment by pocmo** [comment]
Thanks for mentioning that I can edit the raw JSON. I totally missed that and it's super helpful now. :)
