### ISSUE TITLE
The review process is currently not really usable

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#387]
Today you have to look at the history but it really doesn't tells you much.
I would be nicer to see a full diff of what changed.

**Comment by n1k0** [comment]
The main issue with diffing the whole collection is that if ordering of items changes - eg. when sorting by last_modified - it gets easily messy.

**Comment by n1k0** [comment]
After discussing it with @Natim and @leplatrem, a simple yet efficient solution for that would be to consistently order collection records by their ids.

**Comment by n1k0** [comment]
@natim @leplatrem Is there any known way to get the full collection state at a given timestamp? That's basically required to compute a full diff of it between two timestamps... I toyed with the idea of replaying the changes backward up to the start timestamp and started crying out loud.

**Comment by Natim** [comment]
You can use /buckets/bucket-id/collections/collection-id/records?_to=TIMESTAMP

**Comment by n1k0** [comment]
Thanks, I feel *much* better now ;)

**Comment by Natim** [comment]
Also for the specific case of kinto-signer maybe doing a full diff between `/buckets/staging-bucket-id/collections/collection-id/records` and `/buckets/public-bucket-id/collections/collection-id/records`

**Comment by n1k0** [comment]
I'm gonna try avoiding to implement anything specific to kinto-signer, as I think diffing collection states is likely to be a useful feature to everyone.

**Comment by Natim** [comment]
> I think diffing collection states is likely to be a useful feature to everyone.

You mean from the history? Ok sure.

**Comment by n1k0** [comment]
> You mean from the history

yes

**Comment by n1k0** [comment]
This is what I currently have

![](http://i.imgur.com/NHUiwVO.png)

Will test against kinto-writer staging data tomorrow, but I feel like we'll need working on the presentation to make this really usable. Progress though.

**Comment by Natim** [comment]
Yes you can strip records that have a `deleted: true` field if you don't want to see tombstones.
`/buckets/bucket-id/collections/collection-id/records?_before=TIMESTAMP&note_deleted=True`

**Comment by n1k0** [comment]
Perfect, thanks!

**Comment by leplatrem** [comment]
> You can use /buckets/bucket-id/collections/collection-id/records?_before=TIMESTAMP

This won't give you the state of a collection at particular timestamp. This will give you the records of a collection that were not modified before a particular timestamp. 

Only the history (and replaying it backwards) can give you the state of a collection at a particular timestamp.

Note: on the server @oronsan started to work on the feature to revert the changes (which would be interesting for our review/reject use case. cf. https://github.com/Kinto/kinto/pull/862)

**Comment by Natim** [comment]
> This won't give you the state of a collection at particular timestamp.

Indeed you will see every records that has been modified as a new record.

That's why I was suggesting doing a diff for the kinto-signer between the public and staging buckets collections.

**Comment by n1k0** [comment]
> Only the history (and replaying it backwards) can give you the state of a collection at a particular timestamp.

![](https://media0ch-a.akamaihd.net/70/93/c5530e1b45309ecca0cad4c665f7d537.jpg)

**Comment by n1k0** [comment]
> That's why I was suggesting doing a diff for the kinto-signer between the public and staging buckets collections.

This may just be the way to go then, sadly.

**Comment by leplatrem** [comment]
>> This won't give you the state of a collection at particular timestamp.
> 
> Indeed you will see every records that has been modified as a new record.

I don't understand :| AFAIK `_before=X` is just an alias to `max_last_modified=X`.
Or you mean in the diff on the UI?

**Comment by Natim** [comment]
Yes I mean the diff on the UI

**Comment by leplatrem** [comment]
I would be in favor of working on a small *time machine* helper (in `kinto-http.js` for example) to replay the history. I really don't see the difficiulties, please enlight my lantern :D

**Comment by n1k0** [comment]
FWIW a server side implementation of the feature is ongoing at https://github.com/Kinto/kinto/pull/1105 :)
