### ISSUE TITLE
Add comments when requesting/rejecting reviews

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#392]
We could use the collection metadata somehow, or even a dedicated collection to store the comments for example.

Original: https://github.com/Kinto/kinto/issues/1051

**Comment by Natim** [comment]
+1 for a dedicated collection

**Comment by n1k0** [comment]
After discussing this feature with @leplatrem, we decided to keep both the implementation and the UX as simple as possible. The plan for now is:

1. As an editor, after having made changes, I have the ability to leave a comment for the reviewer.
  - The `Request review` button should then open a modal window with a textarea where editors can type their comment, then submitting it. We'll store the comment in the `last_editor_comment` collection attribute. 
2. As a reviewer, when declining changes, I have the ability to leave a comment to the editor. 
  - The `Decline` button should open a modal window where the reviewer can type a comment explaining the reasons why the changes have been declined. We'll store the reviewer comment in the `last_reviewer_comment` collection attribute.
3. When a collection is *pending for approval*, we display the `last_editor_comment`, and when it's in `work in progress` state, we display the `last_reviewer_comment`.

#### Notes

- `Approve` and `Re-sign` buttons shouldn't open a modal window.
- When a review is requested without any comment attached, we should empty the two comment fields.
- (nice to have) Notification emails sent to editors and reviewers might have the comment part of the email body.

We'd like feedback from @pocmo about this plan.

**Comment by n1k0** [comment]
Released in [v1.13.0](https://github.com/Kinto/kinto-admin/releases/tag/v1.13.0).
