### ISSUE TITLE
Login doesn't work with Portier

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto-admin#394]
When I open https://kinto.dev.mozaws.net/v1/admin and switch authentication to Portier, the login flow doesn't work. 

Not sure if this is a Kinto-portier or Kinto-admin issue.

**Comment by n1k0** [comment]
cc @Natim

**Comment by Natim** [comment]
It is probably an issue in kinto-admin because it shows Firefox Account login and then it raises a javascript error.

**Comment by Natim** [comment]
After investigation it is because the kinto-admin doesn't supports Portier auth yet.

**Comment by n1k0** [comment]
Fix ongoing in #395

**Comment by n1k0** [comment]
Fixed by #395
