### ISSUE TITLE
Incorrect permissions displayed (BUG?)

### ISSUE THREAD

**Issue by ryanmark** [Kinto/kinto-admin#399]
The admin does not load the proper permissions for buckets and collections - displaying readonly for many buckets and collections. Tests using the API reveals that the account in question does has write access to these buckets and collections.

It appears this happens because the admin only retrieves the first page of results from `/permissions`, which is may be missing data about the root bucket or collection.

I'm using v1.10.0, but was able to recreate the issue in v1.11.1.

Unfortunately I was not able to track down any bug in the code, but I'm wondering if this is a known issue.

**Comment by n1k0** [comment]
You're correct, it seems we don't request all available pages from the permissions endpoint: https://github.com/Kinto/kinto-admin/blob/master/src/sagas/session.js#L143

This is a bug, thanks for reprting.

**Comment by n1k0** [comment]
Depends on https://github.com/Kinto/kinto-http.js/issues/169

**Comment by n1k0** [comment]
Fix released in [v1.11.2](https://github.com/Kinto/kinto-admin/releases/tag/v1.11.2).

**Comment by ryanmark** [comment]
wow, yall are fast. Thanks!
