### ISSUE TITLE
Confused with result of «Full diff» view

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#402]
0. The collection was signed a end of january

1. I created a record and requested a review:

![screenshot from 2017-03-15 16-38-46](https://cloud.githubusercontent.com/assets/546692/23956826/fc9d92ca-099d-11e7-9016-8a26d95b6750.png)

2. The details brings me to `history?resource_name=record&since=1485291849291`  (which is correct, → `2017-01-24T21:04:09.291Z`) 

3. The details view seems good:

![screenshot from 2017-03-15 16-40-58](https://cloud.githubusercontent.com/assets/546692/23956909/37a38d02-099e-11e7-83e0-de0fc0ee3e6b.png)

4. But the full diff view is not:

![screenshot from 2017-03-15 16-41-49](https://cloud.githubusercontent.com/assets/546692/23956950/55f5892c-099e-11e7-89f8-9d6babab0040.png)

I suspect this is because the history was enabled 3 months ago, where oldest records are 5 months old. But still, I would expect my change to appear on top of the diff, and maybe have extra green stuff at the bottom for the things that were touched before enabling history.

No?

**Comment by n1k0** [comment]
Records are listed by ids to get a consistent diff, so both source and target are listed the very same way, while doing so using last_modified is unlikely to work as records may have been modified meanwhile. 

But I agree this ordering makes no immediate sense (well, no sense at all actually). I don't have a proper solution in mind atm, as it seems hard to sort a *diff* once it's been generated.

**Comment by Natim** [comment]
I would trust the diff more than the history, I actually don't get why we are seeing only one change in the history because I remember we didn't signed all of them. Could it be because the history is only showing changes made by the last user instead of all the changes made since the last signature?

**Comment by n1k0** [comment]
I think some changes are not listed in the table view because history wasn't enabled previously, no? Would there be a way to detect that, and possibly better inform the viewer about it?

**Comment by n1k0** [comment]
After discussing, what needs to be done:

- fetch the earliest ts of the history for that collection (records only)
- filter snapshot and current list to remove all records anterior to that date
- compute diff against these two lists

**Comment by n1k0** [comment]
The problem with the approach mentioned in the last comment is that we'll have an inaccurate diff as we'll be missing information about changes not tracked before the capability has been enabled. I think we should rather trigger an error, eg. *Couldn't retrieve a consistent history back to requested timestamp.* or eq. 

Thoughts?

**Comment by n1k0** [comment]
I feel like checking for full availability of the history range covering the entire period back to the requested timestamp should be part of the kinto-http.js API. I've started experimenting with this idea in https://github.com/Kinto/kinto-http.js/pull/173, feedback welcome.

**Comment by leplatrem** [comment]
Cannot reproduce. History has been enabled for years anyway :D
