### ISSUE TITLE
Links on partial diff view for resource != record? 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#404]
I have this history:
![screenshot from 2017-03-15 16-56-01](https://cloud.githubusercontent.com/assets/546692/23957699/4fd0dd42-09a0-11e7-9c43-086daf73c52c.png)

If I click on every button above the most recent **record entry**, then the resulting view will be empty, which is confusing.

There is something to clarify here: should the partial history include entries of other resources like the actions on collection ?
If not, then the links to partial history should only appear on entry where resource name is record.
If yes, then what would the full diff mean in this context ?

**Comment by n1k0** [comment]
Yeah, we should only provide links next to record related entries, as full diffs for other kind of resources is not supported.

**Comment by n1k0** [comment]
I also realize that we currently only provide full collection diff for *records*, not collection *attributes*. We may want to compute a full diff including them as well, but that would require the ability to comute a snapshot for a single collection object, which kinto-http doesn't provide atm.

**Comment by n1k0** [comment]
Released in [v1.12.0](https://github.com/Kinto/kinto-admin/releases/tag/v1.12.0).
