### ISSUE TITLE
Show last_modified in full diff ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#405]
In diff for single history entries, we show `last_modified` in the diff.  But the **full** diff we don't.

Maybe *full diff* is not the right term for the feature? I mean, if it contains less info :)

**Comment by n1k0** [comment]
I suppressed the `last_modified` and `schema` record properties to improve readability of the diff, but we may want to show them after all. That's why I'm always asking for user feedback tbh.

**Comment by n1k0** [comment]
After discussing it, maybe "Summary diff", or "Changes overview"

**Comment by n1k0** [comment]
Released in [v1.12.0](https://github.com/Kinto/kinto-admin/releases/tag/v1.12.0).
