### ISSUE TITLE
Wrong source of diff for change after signed collection

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#406]
1. A collection is signed.
2. The collection metadata are modified later on.
3. The diff should only show the changes in the collection metadata, not the status changed to signed etc.

> Note: This might be related to kinto-signer or the history plugin on the server side, but let's start from here...

![screenshot from 2017-03-15 17-08-36](https://cloud.githubusercontent.com/assets/546692/23958324/0e2f4778-09a2-11e7-9074-0444112cf64f.png)

**Comment by n1k0** [comment]
> The diff should only show the changes in the collection metadata, not the status changed to signed etc.

Sorry I don't understand. We should swallow these informations?

**Comment by leplatrem** [comment]
> Sorry I don't understand. We should hide this information?

No, it's just that in this particular case the diff *«covers»* the two last actions (status:signed + metadata change) instead of just the last one.

**Comment by leplatrem** [comment]
Seems to be a kinto-signer problem.

**Comment by leplatrem** [comment]
The fix was released in kinto-signer 1.3.1
