### ISSUE TITLE
Limit the number of bucket collections to render in the sidebar 

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#408]
![](http://i.imgur.com/QVvIbnq.png)

If a bucket contains hundreds of collections, the UI is unlikely to scale. We should limit the number of collections to render (eg. 5 most recently updated ones), with a link to see all remaining bucket collections.

Note that the same should apply for the list of buckets.

**Comment by Natim** [comment]
That's why you have the hide readonly checkbox. :)

**Comment by n1k0** [comment]
Sure but still, when unchecked the list is easily messy, no mention of the cost of the initial HTTP requests.

**Comment by n1k0** [comment]
Released in [v1.12.0](https://github.com/Kinto/kinto-admin/releases/tag/v1.12.0).
