### ISSUE TITLE
Edited records are merged or replaced ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#41]
Suppose I have a field in the edited record that is not defined in the schema. Will it be lost upon save when I edit it ?

**Comment by n1k0** [comment]
> Suppose I have a field in the edited record that is not defined in the schema

Forms are built using the schema, how would they have these fields?

Anyway submitted form data are merged with previous record ones [there](https://github.com/Kinto/kinto-admin/blob/master/scripts/actions/form.js#L19-L24).

**Comment by leplatrem** [comment]
> Forms are built using the schema, how would they have such a field?

Let's say one day you have this use-case of having to import the content of an XML file into your Kinto server...

> Anyway submitted form data are merged with previous record ones there. 

Great news :) Thanks !

**Comment by n1k0** [comment]
> Let's say one day you have this use-case of having to import the content of an XML file into your Kinto server...

But then you have the matching JSONschema, no? I'm just trying to understand; are we planning to possibly eventually have mismatching XML and JSON schemas here?
