### ISSUE TITLE
Some fields are randomly displayed as <unknown> on the record list page

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto-admin#412]
See the screenshot:
<img width="992" alt="screen shot 2017-03-17 at 15 29 14" src="https://cloud.githubusercontent.com/assets/167767/24047665/b3f5e93e-0b26-11e7-8ef2-963ac7d959ab.png">

I had other occurrences where other fields were displayed as `<unknown>`, and even one case where it was all three fields. I can confirm that this happens even when the field is filled in.

Here's the schema:
```json
{
  "properties": {
    "activityArn": {
      "description": "ARN for the activity (task aka manual step)",
      "title": "activityArn",
      "type": "string"
    },
    "status": {
      "description": "Status of the step, FAIL or SUCCEED",
      "default": "Unanswered",
      "title": "status",
      "type": "string",
      "enum": [
        "Unanswered",
        "Fail",
        "Succeed"
      ]
    },
    "stateMachineArn": {
      "description": "ARN for the step machine (stepfunction)",
      "title": "stateMachineArn",
      "type": "string"
    }
  },
  "type": "object"
}
```

And the uischema
```json
{
  "ui:order": [
    "stateMachineArn",
    "activityArn",
    "status"
  ]
}
```

**Comment by Natim** [comment]
Unknown is when the field is not present in the record.

**Comment by magopian** [comment]
I understand, but the field is present in the record, as explained above.

**Comment by Natim** [comment]
Then it is quite confusing :s Can you screenshot the JSON view of the record?

**Comment by magopian** [comment]
Sure:

<img width="1023" alt="screen shot 2017-03-17 at 16 02 33" src="https://cloud.githubusercontent.com/assets/167767/24049067/294a8e84-0b2b-11e7-9a48-24dcda9e00c5.png">

**Comment by magopian** [comment]
Forget it, I'm just dumb. Just realised there's a typo in the title name. Sorry for the noise 😭

**Comment by Natim** [comment]
Your displayField is activiryArn

**Comment by n1k0** [comment]
![](https://cdn.meme.am/cache/instances/folder15/56992015.jpg)

**Comment by n1k0** [comment]
Note that we could validate that the names in displayField are valid against the schema. I'm pretty sure we had a PR addressing just that at some point.

**Comment by n1k0** [comment]
Confirmed, we may want to resurrect https://github.com/Kinto/kinto-admin/pull/123
