### ISSUE TITLE
In a bucket with lots of collection, we can only search for visible collection in the sidebar

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#416]
If you go to https://kinto.notmyidea.org/v1 with the kinto-admin and you try searching for `b33` you will not find the collection while [it is present](https://kinto.notmyidea.org/v1/buckets/formbuilder/collections/b33f7d451e774c5c/records?_sort=-last_modified).

**Comment by n1k0** [comment]
That's because the filter box in the sidebar is a filter for displayed entries, not a search engine. Is this issue for making it a search engine? Should we add it separately from the existing filters? I still find the instant filtering feature useful.

**Comment by n1k0** [comment]
Actually we could also still load the full list of collections but only slice them to 10 entries max, and render found entries when users type in the live filter textbox.

**Comment by Natim** [comment]
I think it would be best if we could fetch all the visible collection (thinks that we do with the permission endpoint) and just display some of them but that the search works on all fetched collections.

**Comment by n1k0** [comment]
That's basically what I've just suggested yes.
