### ISSUE TITLE
Pre-commit hook ignores partial commits

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#419]
* `git add -p`
* `git commit -m Partial`
* `git status` → everything was committed instead of just the added changes during `git add -p`

**Comment by Natim** [comment]
Outch 🐞

**Comment by glasserc** [comment]
I don't think we will be able to fix this until https://github.com/okonet/lint-staged/issues/62 is resolved.

**Comment by glasserc** [comment]
Discussion in the linked issue is mostly stalled IMHO, with some useful information supplied by the author of http://pre-commit.com/ which actually handles partially-staged files correctly. I've tried that project and liked it, but it requires installing the pre-commit tool, for example using pip, and explicitly running `pre-commit install` when you clone the repo. How would you feel about moving to that? I'll whip up a PR for discussion.

**Comment by glasserc** [comment]
This should be closed by #445.

**Comment by leplatrem** [comment]
Awesome thanks!
