### ISSUE TITLE
Error when trying to see a diff of the changes for a review.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#432]
In https://kinto-writer.stage.mozaws.net/v1/admin/#/buckets/staging/collections/certificates/history?resource_name=record&since=1493157046812

When clicking on ``View records list diff overview``

I have the following error:

![error](https://cloud.githubusercontent.com/assets/229453/25490743/01e34f76-2b6e-11e7-8916-65ee2a5b19b1.png)

The history is able to give me the list of updates, so it should probably be able to give me the diff since the last update that is in the history.

I that specific case the record existed before I changed it the history of review exists for all impacted record (with the create history record.)

**Comment by leplatrem** [comment]
I don't we'll reproduce/fix that. Closing.
