### ISSUE TITLE
Be able to update and add files with kinto-admin

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#48]

**Comment by Natim** [comment]
Here is how @almet did it with kinto-geophotos: https://github.com/almet/kinto-geophotos/blob/master/admin/js/project.js#L18-L44

**Comment by n1k0** [comment]
Note that rjsx v0.32.0 has been released with file fields https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.32.0

**Comment by leplatrem** [comment]
I saw a demo of this at MozLondon :) Closing !
