### ISSUE TITLE
Notifications banners should overlay and not move the page content

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#501]
![screenshot from 2018-03-27 17-41-07](https://user-images.githubusercontent.com/546692/38002286-1dd2ec6c-31e6-11e8-959f-67062f4ab205.png)

This is disturbing that the page content moves...

**Comment by glasserc** [comment]
I don't really see the problem with this behavior. This way the notification can remain there indefinitely and ensure that it doesn't cover other parts of the page.

**Comment by leplatrem** [comment]
Moving the whole page content is disturbing, and for example your mouse has to move to remain on the same element.
The fact that it remains indefinitely is also annoying because you have to go to the upper right corner to close it...

**Comment by leplatrem** [comment]
Look, this would be excellent:
http://bootstrap-notify.remabledesigns.com/
