### ISSUE TITLE
[signoff] Make it clearer when we only show "changes since the last signature"

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto-admin#503]
https://github.com/Kinto/kinto-admin/blob/fe81b91445d1c6f5ddba7dec4d55cd5f8a627268/src/plugins/signoff/sagas.js#L112

Otherwise, it can just seem like there's a bug where we don't show all the records for some reason.

**Comment by leplatrem** [comment]
Also, we should take into account the fact that collections can be resigned (source.last_modified > preview.last_modified)

**Comment by leplatrem** [comment]
I can't find where this applies. Do you recall @glasserc ?

**Comment by glasserc** [comment]
This might have gotten fixed by https://github.com/Kinto/kinto-admin/pull/936/.

**Comment by glasserc** [comment]
We can't figure out where this issue was applied. It doesn't look like we filter the records to only show those since the last signature.
