### ISSUE TITLE
Add a selector for conflicts resolution strategy

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#51]

**Comment by leplatrem** [comment]
Next to the sync button ?

**Comment by n1k0** [comment]
Yep, ideally.

**Comment by n1k0** [comment]
Woops, pushed this to master directly, while not ready at all for landing. I suspect I'm a little tired these days.

**Comment by n1k0** [comment]
Fun fact googling for doing a revert commit properly first result is this one http://blog.mathieu-leplatre.info/git-annuler-proprement-un-commit-apres-un-push-fr.html /cc @leplatrem :D

**Comment by n1k0** [comment]
Created a proper WiP PR for this in #63.

**Comment by leplatrem** [comment]
> Fun fact googling for doing a revert commit properly, first result is this one http://blog.mathieu-leplatre.info/git-annuler-proprement-un-commit-apres-un-push-fr.html /cc @leplatrem :D 

This is by far the most successful article of my blog :_(
