### ISSUE TITLE
react-router dependency is "stuck"

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto-admin#515]
From #433: upgrading react-router (and react-router-redux) is not currently possible because react-router was a major version upgrade that breaks us in many interesting ways.

> For those of you following along at home, react-router is a major breaking change and it is still rippling through the ecosystem (since June 2017). In particular, we depend on react-router-redux whose current version is 5.0.0-alpha.9. I have a branch at https://github.com/glasserc/kinto-admin/tree/ethan-updates-everything where I tried to update react-router but didn't succeed, instead pulling what I could out and landing it as https://github.com/Kinto/kinto-admin/pull/440. I decided I would check react-router-redux periodically and once it had had a real release, I would try to update again. In the meantime, [this comment](https://github.com/ReactTraining/react-router/issues/5918#issuecomment-361997657) suggests that there will be a mechanism available "eventually" that supports the old (i.e. current) way of doing things, but I don't know when to expect it. In the meantime, let's not upgrade react-router.

This issue will track just the react-router dependency, since it deserves its own issue.

**Comment by glasserc** [comment]
One of the things that broke us previously was react-breadcrumbs. However, https://github.com/svenanders/react-breadcrumbs/issues/99 and https://github.com/svenanders/react-breadcrumbs/pull/105 seem like they may have landed and resolved that, so maybe this is worth taking another swing at.

**Comment by magopian** [comment]
This should be fixed/done in #567
