### ISSUE TITLE
Cannot login with the kinto admin with the account  plugin

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#530]
Before we were able to log into the Kinto Admin using Basic Auth for the account plugin but it is not the case anymore.

**Comment by leplatrem** [comment]
Why is that?

**Comment by Natim** [comment]
It is not recognise as a BasicAuth form so the auth checker only display anonymous: See https://api-staging.chefclub.tools/v1/admin/#/buckets/chefclub/collections?

**Comment by leplatrem** [comment]
Spelling mistake here : https://github.com/Kinto/kinto-admin/blob/f643a081247aff2640a1d95592077d9885f74a25/src/components/AuthForm.js#L16
