### ISSUE TITLE
Handling lots of permissions

### ISSUE THREAD

**Issue by ryanmark** [Kinto/kinto-admin#533]
Hi all, I have a kinto instance with lots of records. Since the permissions endpoint was made mandatory, kinto-admin now takes 15+ minutes to load 10s of pages of permissions from the permissions endpoint before it can be used. Even then it seems to run out of local storage before it completes.

I have paginate_by set to 1000, and probably 20k or so of records in there, total.

Is it possible to avoid loading permissions for every record in the database?
I'm I not supposed to have permissions for every record in kinto? Did I misconfigure something?

Please let me know if I'm asking this in the right place.

**Comment by glasserc** [comment]
That's unfortunate. I think we should only fetch permissions for buckets and collections on startup using `in_resource_name=bucket,collection`. I'm assuming you only have a few of those, right?

**Comment by ryanmark** [comment]
That is a correct assumption

**Comment by glasserc** [comment]
I opened #536 to try to fix this.
