### ISSUE TITLE
Strange validation errors on creating new collection

### ISSUE THREAD

**Issue by peterbe** [Kinto/kinto-admin#535]
(for what it's worth, I was doing this whilst I was testing [this branch](https://github.com/Kinto/kinto-admin/pull/509))

I created a bucket, then from the left-hand nav clicked "Create collection". The only thing I entered before pressing "Create collection" was the "Collection id" field. 
<img width="1616" alt="screen shot 2018-05-18 at 10 35 50 am" src="https://user-images.githubusercontent.com/26739/40244512-0a47f3d0-5a91-11e8-8c8a-95dbc3409fa4.png">

**Comment by leplatrem** [comment]
From what I see, it's not a 400 from the Kinto server...

**Comment by glasserc** [comment]
It looks more like a react-jsonschema-form bug (although I haven't tried to reproduce).

**Comment by glasserc** [comment]
I think what's happening is that react-jsonschema-form is failing to validate the schema that we're using to validate the data to create a collection. The three descriptions that are failing to validate are [these](https://github.com/Kinto/kinto-admin/blob/67eb6fab3f4fee93fd1906af19b8e32e02525eb8/src/components/collection/CollectionForm.js#L111-L148). rjsf switched to ajv a while ago to do its JSON Schema validation, and it may be more strict about what it allows as a legal schema.

**Comment by leplatrem** [comment]
The validation errors also happen in Collection EDIT (collection via curl with PUT)
![screenshot from 2018-05-22 15-58-40](https://user-images.githubusercontent.com/546692/40367363-79a70e82-5dd9-11e8-992b-a01b74282789.png)

This happens on Remote settings STAGE/PROD, we'll have to raise the priority of the bug

![screenshot from 2018-05-22 15-58-40](https://user-images.githubusercontent.com/546692/40367378-84efb2c6-5dd9-11e8-9132-8c0d697f8f68.png)
