### ISSUE TITLE
Unclear errror message with OpenId Connect

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#559]
![screenshot from 2018-06-28 18-08-27](https://user-images.githubusercontent.com/546692/42046499-55a44a8a-7afe-11e8-878c-19adb7b54de3.png)

it shouldn't say «and UserID is undefined». Also it shouldn't show `openid-auth0` since it's our internal sauce :)

**Comment by magopian** [comment]
Makes sense, what would you like the error message to be? Simply "Authentication failed" without any additional info?

**Comment by leplatrem** [comment]
I think that the specific case is when userID is undefined.

> what would you like the error message to be?

I guess that something like `Authenticated failed > Could not authenticate with OpenID Connect (Auth0)` would be great
