### ISSUE TITLE
devServer.js should support a -c argument

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto-admin#56]
This would make it easier to develop kinto-admin against a local kinto (although this sort of situation would probably be rare).

I tried implementing this but I wanted to share the `check` function for the `-c` argument from `bin/kinto-admin` and I couldn't figure out how to do it. One ugly way is to have devServer.js `require("./bin/kinto-admin")`, but I couldn't bring myself to commit this. I couldn't figure out how to have `bin/kinto-admin` able to `require` stuff from `scripts` when it was run directly and from `node_modules` when the user had `npm install`'d kinto-admin.

**Comment by n1k0** [comment]
Not relevant anymore since #65 has landed.
