### ISSUE TITLE
Upgrade React from 15.x to 16.x

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto-admin#564]
This would give us access to https://reactjs.org/docs/fragments.html for example (which would be very useful to properly fix #562), and keep up to date with the main dependency of the project.

Regarding [upgrading React itself](https://reactjs.org/blog/2017/09/26/react-v16.0.html#upgrading) it should be rather straightforward, but we might encounter issues with dependencies, and deprecations (like `react-addons-test-utils` which [needs to be migrated](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#discontinuing-support-for-react-addons)).

**Comment by leplatrem** [comment]
See #515
