### ISSUE TITLE
Link the resolve button on the conflict error message.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#57]
![resolve-button](https://cloud.githubusercontent.com/assets/229453/15107280/2bf138e2-15cf-11e6-9caa-95e34b9040cf.png)

We should add an easy way to resolve the conflict from the error message.

**Comment by n1k0** [comment]
The problem is we can get many conflicts, so once you'd click a link from the notification entry you'd lose the others. Persisted stateful notifications might be a solution here but that would mean a large refactoring of them, and I'm not sure it's worth it.

**Comment by Natim** [comment]
Cannot we have a page with all the conflict and as soon as you select one it disappear from the page?

**Comment by Natim** [comment]
Or maybe we can just add a button for each conflict and after the person clicked on one, it will use the other resolve button for the other conflict.

Most of the time there will be not conflict and ofter only one so I think it could be enough.

**Comment by n1k0** [comment]
> Cannot we have a page with all the conflict and as soon as you select one it disappear from the page?

The current records list page with highlighted conflicting rows isn't enough?

**Comment by Natim** [comment]
> The current records list page with highlighted conflicting rows isn't enough?

Yes but it displays only one conflict, I was suggesting displaying all conflicts on it, a bit like: The current records list page with highlighted conflicting rows isn't enough?

**Comment by n1k0** [comment]
> Yes but it displays only one conflict

Wüt?

![](http://i.imgur.com/UVlRkoa.png)

**Comment by Natim** [comment]
You are right this page is probably enough :+
