### ISSUE TITLE
Display a busy state whenever the server info is fetched

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto-admin#579]
At the moment the auth form displays a weird state with only the anonymous auth type available, until the server info and its capabilities are fetched and received. Instead we should
1/ display only the server history bar
2/ as soon as a server is selected (or on mount), when we call `getServerInfo`, display a spinner
3/ when the server capabilities are received, display the proper auth methods radio buttons
4/ if fetching the server capabilities fails, keep the spinner on, display the error message
5/ if another server is selected from the server history dropdown (or a new one entered in the text input), cancel (or discard) the current `getServerInfo` call

This should properly fix issues like #577 or https://github.com/Kinto/kinto-admin/pull/509#issuecomment-389901873

**Comment by alexcottner** [comment]
Closed with [PR 3050](https://github.com/Kinto/kinto-admin/pull/3050).
