### ISSUE TITLE
Display canonical JSON form to ease comparison

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#58]
![canonical-json](https://cloud.githubusercontent.com/assets/229453/15107307/5a5bf9f6-15cf-11e6-9ee8-9a80b027d69e.png)

Please tell me the differences between the two :)

**Comment by n1k0** [comment]
last_modified differs.

**Comment by n1k0** [comment]
Oh, the issue is about rendering a diff, okay ;)

**Comment by n1k0** [comment]
Most interesting lib found for now is https://github.com/flitbit/diff

**Comment by n1k0** [comment]
Fixed by #61
