### ISSUE TITLE
Detect when the conflict actually contains twice the same record.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#59]
In this specific case, both records contains the same data (even if it is hard to tell)

Picking one or the other will have the same impact.

![canonical-json](https://cloud.githubusercontent.com/assets/229453/15107350/9870dafe-15cf-11e6-864d-8fd003ddb464.png)

**Comment by n1k0** [comment]
I'm very surprised kinto.js marks this as a conflict as it's not supposed to happen if both data objects are actually equals...

**Comment by n1k0** [comment]
Also sounds like someything to do is process the json string representation to at least order the keys, so visually comparing these would be *much* easier.

**Comment by Natim** [comment]
Apparently the schema value is different

**Comment by n1k0** [comment]
That explains it.

Side note, you may be interested in tools like [json-diff](https://www.npmjs.com/package/json-diff) to quickly check for diffs. Another side note, we should probably leverage such a lib in the admin itself so we could display a diff!

**Comment by n1k0** [comment]
Also, should the schema version value being different raise a conflict here? I feel like it shouldn't, as the two record data objects are compatible.

**Comment by Natim** [comment]
Yes IMHO the schema value should be cleaned as for last_modified and id values.

**Comment by leplatrem** [comment]
Closing since no offline sync anymore.
