### ISSUE TITLE
Cannot edit collection metadata without display fields defined

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#621]
* Create a collection without display fields
* Edit attributes
* Cannot save. 

--> it should be left undefined or left with id and last_modified as default

**Comment by alexcottner** [comment]
@leplatrem - Is this issue no longer valid? It looks like we throw a custom validation error telling users we require at least one display field. 
![Screenshot from 2023-11-14 10-00-39](https://github.com/Kinto/kinto-admin/assets/148472676/192d69c2-16c1-4d2c-865a-f300a7babc49)

**Comment by leplatrem** [comment]
Sorry @alexcottner I must have been clearer on the description.

The first step has to be done via the API. For example:

```
http PUT "${SERVER}/v1/buckets/main-workspace/collections/test-empty-metadata" "Authorization: ${AUTHZ}"
```

**Comment by alexcottner** [comment]
Oh perfect, that was my missing context. So in that case we have a mismatch between our UI validation and what the API allows in. I'm guessing the API is correct here so I will open these rules up to allow for inserts/updates without display fields.
