### ISSUE TITLE
Page crash if user sets wrong ui:widget

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#625]
![screenshot from 2018-09-27 18-18-02](https://user-images.githubusercontent.com/546692/46159893-b7802b00-c281-11e8-88c4-4ad403baf765.png)

It should probably be better to show an error within the UI

**Comment by alexcottner** [comment]
How does this look?

![image](https://github.com/Kinto/kinto-admin/assets/148472676/d7c4a45e-010f-4d2a-a1d7-97757fd93edb)
