### ISSUE TITLE
If collection creation is not allowed, form shows confusing message

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#633]
- bucket is readonly
- no permission to create collection
- button is shown anyway (see #86)
- Create collection form says something about «edit»
![screenshot from 2018-09-28 16-09-40](https://user-images.githubusercontent.com/546692/46213555-1f457d00-c339-11e8-921d-c074296739c6.png)

**Comment by alexcottner** [comment]
I cannot reproduce this fully, perhaps it's already been fixed? When I see a read-only collection now the "Create collection" button is missing from the sidebar. However I can see it on the collections list. I'll fix the second button showing up.
![image](https://github.com/Kinto/kinto-admin/assets/148472676/f20f10d0-30c7-47a4-9943-1fde9513f32a)

**Comment by leplatrem** [comment]
Indeed, I think both things need to be fixed:
- remove the `Create collection` when readonly
- fix the message `You don't have the required permission to edit this collection.` when a user reaches to the URL directly with `#/buckets/{bid}/collections/create`  (or redirect to list with a notification, if you find that clearer)
