### ISSUE TITLE
Add the ability to hide buckets / collections that I've only got read access to.

### ISSUE THREAD

**Issue by almet** [Kinto/kinto-admin#685]
When using the admin and I connect with a set of credentials, I always see a lot of buckets that I don't really care about. I see them because I've got read access to them, but they are mostly irrelevant to me.

Would it make sense to just group them under a "read only buckets and collections" group, so that they don't clutter the interface?

What do you think?

**Comment by glasserc** [comment]
There's a `Show readonly buckets/collections` checkbox that defaults to off. Would turning that off declutter the interface sufficiently?

**Comment by leplatrem** [comment]
In version 1.22, we hide readonly by default. I'm tempted to close this issue :)

**Comment by almet** [comment]
Yep, closing!

**Comment by almet** [comment]
They actually appear to be collections that anyone can write into. Not sure if there is a way to hide them too…
