### ISSUE TITLE
When I click "load more" the app gets me to the end of the page

### ISSUE THREAD

**Issue by almet** [Kinto/kinto-admin#686]
Which can be problematic if I have access to a lot of collections / buckets, since the end of the page is mostly blank.

**Comment by leplatrem** [comment]
Oh! Interesting!

We should get the Y coordinate of the list bottom instead.

https://github.com/Kinto/kinto-admin/blob/c05dacfdcfa4449f0d132444186140426127c10b/src/sagas/collection.js#L77

**Comment by almet** [comment]
That would make sense, yes!
