### ISSUE TITLE
When I ctrl-click on the edit button, I need to authenticate again

### ISSUE THREAD

**Issue by almet** [Kinto/kinto-admin#687]
While trying to find a way to edit multiple records in batch, I've tried to open the edition form in as-many separate tabs as records I wanted to edit.

But when going to these newly created tabs, I'm presented with the authentication form (even if I'm already identified !)

**Comment by n1k0** [comment]
There's a a sessionStorage event you can subscribe to listen for changes performed outside of the current page environment. It looks like this:

```js
// Ensure session is refreshed when it changes in another tab/window
window.addEventListener("storage", (event) => {
  if (event.storageArea === sessionStorage && event.key === storeKey) {
    updateSessionData(event.newValue);
  }
}, false);
```

**Comment by alexcottner** [comment]
This is annoying me when testing things so I'm moving it into the current milestone
