### ISSUE TITLE
Add the ability to filter by field

### ISSUE THREAD

**Issue by almet** [Kinto/kinto-admin#688]
It could be interesting to offer the possibility to filter the records by entering some text in a field (the records shown would be the ones which match), a bit like it's possible to do on a spreadsheet for instance.

Here is a capture of what it looks like in a spreadsheet editor:

![](https://www.shorttutorials.com/google-docs-spreadsheet/images/filter-google-spreadsheet3.jpg)

**Comment by leplatrem** [comment]
Duplicate of #442
