### ISSUE TITLE
Unable to list a read only collection as anonymous since 1.22

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#698]
Since kinto-admin 1.22 I am now unable to open a read-only collection as anonymous.

You can try https://api-staging.chefclub.tools/v1/admin/#/buckets/chefclub-v2/collections/books/records for instance

**Comment by leplatrem** [comment]
![screenshot from 2018-11-20 12-03-46](https://user-images.githubusercontent.com/546692/48769634-6e19ee00-ecbc-11e8-8df0-9b436e7b98d0.png)

**Comment by leplatrem** [comment]
![Screenshot from 2019-05-30 11-29-56](https://user-images.githubusercontent.com/546692/58623468-586e2c80-82ce-11e9-98ba-7c6274e1788d.png)

Cannot reproduce... @Natim ?
