### ISSUE TITLE
Validate provided collection JSON schema

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#75]
I've just spent a few unecessary minutes trying to figure out a weird error I had in the admin because I misspelled `properties` in my schema, while it was accepted just fine when submitted.

We should validate the entered JSON schema, eg. using https://github.com/mafintosh/is-my-json-valid.

**Comment by n1k0** [comment]
> We should validate the entered JSON schema, eg. using https://github.com/mafintosh/is-my-json-valid.

WELL, probably not.

![](http://i.imgur.com/ON1w3C6.png)

**Comment by Natim** [comment]
We already have a JSON schema validator actually.

**Comment by Natim** [comment]
https://github.com/Kinto/kinto/blob/master/kinto/views/collections.py#L24

**Comment by n1k0** [comment]
Well, could it e tweaked a little then? Entering this doesn't make it fail :/

```json
{
  "type": "object",
  "porperties": {
    "content": {
      "type": "string"
    },
    "title": {
      "type": "string"
    }
  }
}
```

**Comment by n1k0** [comment]
For example if there's an option to disallow unknown JSON schema property names in the schema itself, that would be nice.

**Comment by leplatrem** [comment]
Duplicate of #253 ?

**Comment by n1k0** [comment]
Not really, here the purpose would be to check that the entered json schema actually matches the json schema spec.

**Comment by alexcottner** [comment]
Closed with [PR 3043](https://github.com/Kinto/kinto-admin/pull/3043).
