### ISSUE TITLE
Add ability to scan a bucket?

### ISSUE THREAD

**Issue by aegaas** [Kinto/kinto-admin#79]
Hello,

our project uses generated names of collections on an oauth application's bucket, therefore we cannot predict collection or bucket names. Being able to "scan" a bucket for collections within the kinto admin would be amazing, and before we have this ability, it doesn't make sense to integrate kinto-admin into our growing suite of tools.

Thanks for all your hard work on this project, and I hope that you include this feature in the future! I'll keep an eye out.

**Comment by Natim** [comment]
Why ``GET /buckets`` doesn't works for you? Did you try the last kinto-admin? It does just that (discovering buckets and collections)

What are the permission on your bucket/collection?

**Comment by aegaas** [comment]
according to the definition of the .json configuration file here https://www.npmjs.com/package/kinto-admin the "collections" option is required.

When the collection option is empty, I get a strange error:

Info[5/24/2016, 9:04:53 PM]

> Given action "COLLECTIONS_LIST_RECEIVED", reducer "collections" returned undefined. To ignore an action, you must explicitly return the previous state.

I guess what I'm asking for is a true explorer feature where I don't need to configure every collection, since I don't know much about them prior to exploring them (my users will be able to make their own schemas and records)

**Comment by Natim** [comment]
Then try this: http://kinto.github.io/kinto-admin/

**Comment by n1k0** [comment]
I'm closing this as the need described is addressed by current master. Watch for the next upcoming release :)

**Comment by aegaas** [comment]
Thank you gentlemen, I was able to try it with the master version this morning and its working great!
