### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by prasanthgq** [Kinto/kinto-admin#8]
This URL http://kinto.github.io/kinto-admin/ in github seems to be not working

**Comment by n1k0** [comment]
What browser are you using? works fine on latest Firefox and Chrome.

**Comment by Natim** [comment]
@prasanthgq Could you also add a screenshot please?

**Comment by prasanthbpillai** [comment]
Hi Natim,

It looks like some issue with JS rendering in my browser. I cleared the cache and it is back to normal.

Thanks for the follow up.

**Comment by Natim** [comment]
Perfect then
