### ISSUE TITLE
(minor) Validate collection id/name

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#82]
![capture d ecran de 2016-05-24 11-50-16](https://cloud.githubusercontent.com/assets/546692/15499690/bb4344f4-21a5-11e6-8803-e4a33f622316.png)

Idea: use the current field to populate a `label` attribute, and slugify to assign the `id` attribute to be used.

**Comment by n1k0** [comment]
As a simpler solution, we could also add the same regexp validation rule as the one used on the server in the form schema.
