### ISSUE TITLE
Add button to copy Authorization header value to the clipboard

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#915]
Currently when a user wants to run script, the only way to obtain a Bearer token is to login in the Admin UI, open the dev tools, and copy the autorization header from the completed network requests.

We could at least have a small button close to the username that copies the authorization header value to the clipboard.

**Comment by vanillajonathan** [comment]
The button is visible even when using anonymous authentication where there is nothing copy.
