### ISSUE TITLE
Cannot run tests or app locally

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#925]
I'm having tons of errors when trying to run tests or start app:

```bash
$ rm -rf node_modules
$ npm ci  # use package-lock.json
$ npm run test
```

```
$ npm --version
6.9.0
$ node --version
v10.9.0

```

Among the errors: 

* `TypeError: Cannot read property 'querySelector' of undefined`
* `Error: Uncaught [Error: Invariant failed: You should not use <Link> outside a <Router>]`
* `TypeError: Cannot read property 'querySelectorAll' of null`
* `TypeError: Cannot read property '0' of undefined`
* `AssertError: expected getServerInfo to be called with exact arguments`
* `TypeError: Cannot read property 'text' of undefined`

But tests pass on CI on master :(  :( https://travis-ci.org/Kinto/kinto-admin/builds/536227824?utm_source=github_status&utm_medium=notification

@glasserc @Natim any idea?

**Comment by Natim** [comment]
All I can say is that with my current node_modules npm run test passes locally.

$ node --version
v8.11.3
$ npm --version
6.1.0

**Comment by Natim** [comment]
After running npm install everything is broken too.

**Comment by leplatrem** [comment]
> After running npm@6.9.0 install everything is broken too.

Oh shit. I doubt that downgrading to 6.1.0 will solve it back. There's a set of dependencies that is pulled which does not work.... 
Question is....how does it work on Travis?

**Comment by leplatrem** [comment]
Good news, I can have the tests pass when checkouting the latest tag `v1.23.0`.

I'll bisect and see...

![](https://media.giphy.com/media/ZLWRirnpNw7Mk/source.gif)

**Comment by leplatrem** [comment]
This commit 1d804bc8ad23a5d5e1454194d9a5162726d840ec makes the tests fail with `AssertionError: expected 'number' to deeply equal 'text'`

Question remains: why does it work on Travis...
