### ISSUE TITLE
Add ui:help for the displayField field in the collection properties form

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#93]
Spawned from #91.

**Comment by Natim** [comment]
Is a placeholder sufficient? (I know I am lazy)

![placeholder](https://cloud.githubusercontent.com/assets/229453/15654064/58d32ce4-2691-11e6-9747-61fda325b1fe.png)

**Comment by n1k0** [comment]
Yes!

**Comment by Natim** [comment]
I did the two solutions in https://github.com/Kinto/kinto-admin/pull/94
Tell me which one you prefer and I will remove the unwanted commit.

**Comment by n1k0** [comment]
Closed by #94.
